mod advanced;
pub mod burn;
mod exe;
pub mod inno;
mod installshield;
mod msi;
pub mod msix_family;
pub mod nsis;
mod sevenzip_sfx;
pub mod utils;
mod zip;

pub use advanced::AdvancedInstaller;
pub use burn::Burn;
pub use exe::Exe;
pub use installshield::InstallShield;
pub use msi::Msi;
pub use nsis::Nsis;
pub use sevenzip_sfx::SevenZipSfx;
pub use zip::Zip;
